# Generated by Django 4.0.3 on 2022-04-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('highlight', 'highlight'), ('middle', 'middle'), ('low', 'low')], max_length=15)),
                ('created', models.DateField(auto_now=True)),
                ('due', models.DateField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
